apiVersion: apps/v1
kind: Deployment
metadata:
  name: onesg-deployment
  labels:
    app: onesg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onesg
  template:
    metadata:
      labels:
        app: onesg
    spec:
      containers:
      - name: onesg
        image: gcr.io/onesg-111999/github.com/billrain/onesg/green@sha256:d8cc48d8c34af52752a349f617f66e761c066e06eb4f4f121efd61cf0c21f1a0
        ports:
        - containerPort: 5000
