apiVersion: v1
kind: Service
metadata:
  name: onesg
  labels:
    app: onesg
spec:
  selector:
    app: onesg
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: "35.197.144.41"
